#!/bin/sh -eu

cast_audio () {
    pacat --format=float32le --rate=24000 --channels=1
}

cast_subcarrier () {
    nice ./fm_subcarrier_raw_tx.py -f 64000 -v 3000
}

cd "`dirname $0`"
tmpfile=`mktemp --tmpdir tmp.XXXXXXXXXX.raw`
ln -sf /dev/stdout $tmpfile

stdbuf -oL ssh -T ${1:-irc-source} |
    sed -ur 's/^/\r/' |
    minimodem --tx-carrier --float-samples -t 100 -R 24000 --ascii -f $tmpfile |
    cast_${CAST:-subcarrier}
